2025-04-21 10:55:39,778 INFO: Application startup [in C:\Users\laolu\OneDrive\Desktop\SCRAPPY SCHEDULER\app\__init__.py:82]
2025-04-21 10:55:56,159 ERROR: Exception on /auth/forgot_password [POST] [in C:\Users\laolu\AppData\Roaming\Python\Python312\site-packages\flask\app.py:1414]
Traceback (most recent call last):
  File "C:\Users\laolu\AppData\Roaming\Python\Python312\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\laolu\AppData\Roaming\Python\Python312\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\laolu\AppData\Roaming\Python\Python312\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\laolu\AppData\Roaming\Python\Python312\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\laolu\OneDrive\Desktop\SCRAPPY SCHEDULER\app\auth\routes.py", line 55, in forgot_password
    send_password_reset_email(user)
  File "C:\Users\laolu\OneDrive\Desktop\SCRAPPY SCHEDULER\app\email.py", line 16, in send_password_reset_email
    msg.html = render_template('auth/email/reset_password.html',
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\laolu\AppData\Roaming\Python\Python312\site-packages\flask\templating.py", line 150, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\laolu\AppData\Roaming\Python\Python312\site-packages\jinja2\environment.py", line 1081, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\laolu\AppData\Roaming\Python\Python312\site-packages\jinja2\environment.py", line 1010, in get_template
    return self._load_template(name, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\laolu\AppData\Roaming\Python\Python312\site-packages\jinja2\environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\laolu\AppData\Roaming\Python\Python312\site-packages\jinja2\loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\laolu\AppData\Roaming\Python\Python312\site-packages\flask\templating.py", line 64, in get_source
    return self._get_source_fast(environment, template)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\laolu\AppData\Roaming\Python\Python312\site-packages\flask\templating.py", line 98, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: auth/email/reset_password.html
2025-04-21 11:03:52,782 INFO: Application startup [in C:\Users\laolu\OneDrive\Desktop\SCRAPPY SCHEDULER\app\__init__.py:82]
2025-04-21 11:04:15,510 ERROR: Exception on /auth/forgot_password [POST] [in C:\Users\laolu\AppData\Roaming\Python\Python312\site-packages\flask\app.py:1414]
Traceback (most recent call last):
  File "C:\Users\laolu\AppData\Roaming\Python\Python312\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\laolu\AppData\Roaming\Python\Python312\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\laolu\AppData\Roaming\Python\Python312\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\laolu\AppData\Roaming\Python\Python312\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\laolu\OneDrive\Desktop\SCRAPPY SCHEDULER\app\auth\routes.py", line 55, in forgot_password
    send_password_reset_email(user)
  File "C:\Users\laolu\OneDrive\Desktop\SCRAPPY SCHEDULER\app\email.py", line 16, in send_password_reset_email
    msg.html = render_template('auth/email/reset_password.html',
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\laolu\AppData\Roaming\Python\Python312\site-packages\flask\templating.py", line 150, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\laolu\AppData\Roaming\Python\Python312\site-packages\jinja2\environment.py", line 1081, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\laolu\AppData\Roaming\Python\Python312\site-packages\jinja2\environment.py", line 1010, in get_template
    return self._load_template(name, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\laolu\AppData\Roaming\Python\Python312\site-packages\jinja2\environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\laolu\AppData\Roaming\Python\Python312\site-packages\jinja2\loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\laolu\AppData\Roaming\Python\Python312\site-packages\flask\templating.py", line 64, in get_source
    return self._get_source_fast(environment, template)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\laolu\AppData\Roaming\Python\Python312\site-packages\flask\templating.py", line 98, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: auth/email/reset_password.html
2025-04-21 11:06:25,306 INFO: Application startup [in C:\Users\laolu\OneDrive\Desktop\SCRAPPY SCHEDULER\app\__init__.py:82]
2025-04-21 11:06:37,467 ERROR: Exception on /auth/forgot_password [POST] [in C:\Users\laolu\AppData\Roaming\Python\Python312\site-packages\flask\app.py:1414]
Traceback (most recent call last):
  File "C:\Users\laolu\AppData\Roaming\Python\Python312\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\laolu\AppData\Roaming\Python\Python312\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\laolu\AppData\Roaming\Python\Python312\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\laolu\AppData\Roaming\Python\Python312\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\laolu\OneDrive\Desktop\SCRAPPY SCHEDULER\app\auth\routes.py", line 55, in forgot_password
    send_password_reset_email(user)
  File "C:\Users\laolu\OneDrive\Desktop\SCRAPPY SCHEDULER\app\email.py", line 18, in send_password_reset_email
    mail.send(msg)
  File "C:\Users\laolu\AppData\Roaming\Python\Python312\site-packages\flask_mail\__init__.py", line 539, in send
    with self.connect() as connection:
         ^^^^^^^^^^^^^^
  File "C:\Users\laolu\AppData\Roaming\Python\Python312\site-packages\flask_mail\__init__.py", line 127, in __enter__
    self.host = self.configure_host()
                ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\laolu\AppData\Roaming\Python\Python312\site-packages\flask_mail\__init__.py", line 152, in configure_host
    host.login(self.mail.username, self.mail.password)
  File "C:\Python312\Lib\smtplib.py", line 750, in login
    raise last_exception
  File "C:\Python312\Lib\smtplib.py", line 739, in login
    (code, resp) = self.auth(
                   ^^^^^^^^^^
  File "C:\Python312\Lib\smtplib.py", line 662, in auth
    raise SMTPAuthenticationError(code, resp)
smtplib.SMTPAuthenticationError: (534, b'5.7.9 Application-specific password required. For more information, go to\n5.7.9  https://support.google.com/mail/?p=InvalidSecondFactor 46e09a7af769-730047ca051sm1491041a34.36 - gsmtp')
2025-04-22 09:53:10,355 INFO: Application startup [in C:\Users\laolu\OneDrive\Desktop\SCRAPPY SCHEDULER\app\__init__.py:82]
